const colors = {
  light: {
    text: '#24151B',
    tint: '#B9536B',
    background: '#FFF9FA',
    foreground: '#24151B',
    card: '#FFFFFF',
    cardForeground: '#24151B',
    primary: '#B9536B',
    primaryForeground: '#FFFFFF',
    secondary: '#FFF0F2',
    secondaryForeground: '#24151B',
    muted: '#FFF0F2',
    mutedForeground: '#8C6570',
    accent: '#B9536B',
    accentForeground: '#FFFFFF',
    destructive: '#ef4444',
    destructiveForeground: '#FFFFFF',
    border: 'transparent',
    input: '#FFF0F2',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#D96A82',
    background: '#120B10',
    foreground: '#FFFFFF',
    card: '#21151D',
    cardForeground: '#FFFFFF',
    primary: '#D96A82',
    primaryForeground: '#FFFFFF',
    secondary: '#2B1A25',
    secondaryForeground: '#FFFFFF',
    muted: '#2B1A25',
    mutedForeground: '#9385B8',
    accent: '#FF4473',
    accentForeground: '#FFFFFF',
    destructive: '#ef4444',
    destructiveForeground: '#FFFFFF',
    border: 'transparent',
    input: '#21151D',
  },
  radius: 16,
};

export default colors;
