import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Lock } from 'phosphor-react-native';
import { T } from '@/constants/theme';
import { getPrivateMessage, markPrivateMessageRead, purchasePrivateAttachment, replyToPrivateMessage, type PrivateMessage } from '@/services/private-inbox';
import { useAuth } from '@/contexts/AuthContext';

export default function PrivateThread() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { user } = useAuth(); const [message, setMessage] = useState<PrivateMessage | null>(null); const [body, setBody] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  const load = useCallback(async () => { if (!id) return; try { const m = await getPrivateMessage(id); setMessage(m); if (m.recipient_id === user?.id) await markPrivateMessageRead(id); } catch {} finally { setLoading(false); } }, [id, user?.id]); useEffect(() => { load(); }, [load]);
  const reply = async () => { if (!message || !body.trim()) return; setSending(true); try { const result = await replyToPrivateMessage(message.id, body.trim()); setMessage((m) => m ? { ...m, reply: result.message, status: 'replied' } : m); setBody(''); } catch (e) { Alert.alert('Could not reply', e instanceof Error ? e.message : 'Please try again.'); } finally { setSending(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator color={T.ACCENT} /></View>; if (!message) return <View style={styles.center}><Text style={styles.text}>Message not found.</Text></View>;
  const renderAttachment = (a: any) => a.is_locked ? <Pressable key={a.id} style={styles.locked} onPress={async () => { try { const r = await purchasePrivateAttachment(a.id); setMessage((m) => m ? { ...m, reply: m.reply ? { ...m.reply, attachments: m.reply.attachments.map((x) => x.id === a.id ? r.attachment : x) } : m } : m); } catch (e) { Alert.alert('Could not unlock', e instanceof Error ? e.message : 'Please try again.'); } }}><Lock color={T.TEXT} /><Text style={styles.text}>Unlock attachment · ₦{a.price.toLocaleString()}</Text></Pressable> : <Text key={a.id} style={styles.attachment}>Attachment available ({a.media_type})</Text>;
  return <View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()}><ArrowLeft color={T.TEXT} /></Pressable><Text style={styles.title}>Correspondence</Text><View /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.label}>From</Text><Text style={styles.text}>{message.sender_name ?? message.sender_username ?? message.sender_id}</Text><Text style={styles.date}>{new Date(message.created_at).toLocaleString()}</Text><View style={styles.card}><Text style={styles.text}>{message.body}</Text>{message.attachments.map(renderAttachment)}</View>{message.reply ? <><Text style={styles.label}>Creator replied</Text><View style={styles.card}><Text style={styles.text}>{message.reply.body}</Text>{message.reply.attachments.map(renderAttachment)}</View></> : message.recipient_id === user?.id ? <><Text style={styles.label}>Reply</Text><TextInput value={body} onChangeText={setBody} multiline placeholder="Write a reply…" placeholderTextColor={T.TEXT_3} style={styles.input} /><Pressable style={styles.button} onPress={reply} disabled={sending || !body.trim()}>{sending ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Send Reply</Text>}</Pressable></> : null}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: T.BG, padding: 18 }, center: { flex: 1, backgroundColor: T.BG, alignItems: 'center', justifyContent: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14 }, title: { color: T.TEXT, fontFamily: T.FONT.bold, fontSize: 19 }, content: { gap: 10, paddingBottom: 40 }, label: { color: T.TEXT_3, fontSize: 12, marginTop: 10 }, text: { color: T.TEXT, lineHeight: 22 }, date: { color: T.TEXT_3, fontSize: 11 }, card: { padding: 16, backgroundColor: T.SURFACE, borderRadius: 14, gap: 12 }, input: { minHeight: 130, padding: 14, backgroundColor: T.SURFACE, borderRadius: 14, color: T.TEXT, textAlignVertical: 'top' }, button: { padding: 16, borderRadius: 28, backgroundColor: T.ACCENT, alignItems: 'center' }, buttonText: { color: '#fff', fontFamily: T.FONT.semibold }, locked: { flexDirection: 'row', gap: 8, alignItems: 'center', padding: 12, backgroundColor: T.SURFACE_2, borderRadius: 10 }, attachment: { color: T.TEXT_2, fontSize: 12 } });
